version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8084"
    depends_on:
      - mariadb
    volumes:
      - wordpress-data:/var/www/html:rw
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    ports:
      - 3006
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    image: nginx:latest
    # command: nginx -s reload
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:rw
      - wordpress-data:/var/www/html:rw
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-data:/var/www/certbot:rw
    depends_on:
      - wordpress
      - mariadb
      - phpmyadmin
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      mode: global
      placement:
        constraints:
          - node.role == manager

  ## One nginx to get certbot certificates using only 80 port, and one up when certificates are presents with only port 443
  nginx-ssl:
    image: nginx:latest
    # command: nginx -s reload
    restart: always
    ports:
      - 443:443
    volumes:
      - ./nginx-ssl/conf:/etc/nginx/conf.d:rw
      - wordpress-data:/var/www/html:rw
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-data:/var/www/certbot:rw
    depends_on:
      - certbot
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
        window: 120s
      mode: global
      placement:
        constraints:
          - node.role == manager

  certbot:
    image: certbot/certbot:latest
    command: certonly --cert-name ${DOMAINNAME} --webroot --webroot-path /var/www/certbot --email maiiwen@42l.fr --agree-tos --no-eff-email -d wp.${DOMAINNAME} -d pma.${DOMAINNAME} --test-cert --force-renewal
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-logs:/var/log/letsencrypt:rw
      - certbot-data:/var/www/certbot:rw
    depends_on:
      - nginx
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      mode: global
      placement:
        constraints:
          - node.role == manager

volumes:
  wordpress-data:
  mariadb-data:
  certbot-conf:
  certbot-logs:
  certbot-data:
