version: '3'

services:
  wordpress:
    build:
        context: .
        dockerfile: ./wordpress/Dockerfile
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    ports:
      - 8084:80
    volumes:
      - ./wordpress-data:/var/www/html:rw
    depends_on:
      - mariadb
    
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
#      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:rw
      - ./wordpress-data:/var/www/html:rw
#      - ./certbot/conf:/etc/nginx/ssl
#      - ./certbot/data:/var/www/html
    depends_on:
      - phpmyadmin
      - wordpress

  mariadb: 
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mariadb-data:/var/lib/mysql:rw

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb

  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --webroot-path=/var/www/html --email youremail@domain.com --agree-tos --no-eff-email -d domain.com -d www.domain.com
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/logs:/var/log/letsencrypt
  #     - ./certbot/data:/var/www/html
    
volumes:
  wordpress-data:
  mariadb-data:
